- name: Build image
  run: docker build -t $IMAGE_NAME

- name: Scan image
  uses: PaloAltoNetworks/prisma-cloud-scan@v1
  with: 
pcc_console_url: ${{ secrets.PCC_CONSOLE_URL }}
pcc_user: ${{ secrets.PCC_USER }}
pcc_pass: ${{ secrets.PCC_PASS }}
image_name: ${{ env.IMAGE_NAME }}
